name: Renovate

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: Set Renovate log level
        type: choice
        default: info
        options:
          - info
          - debug
  schedule:
    - cron: "0 5 * * 0"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      - name: Run Renovate
        uses: renovatebot/github-action@13da59cf7cfbd3bfea72ce26752ed22edf747ce9  # v43.0.2
        env:
          LOG_LEVEL: ${{ inputs.log_level || 'info' }}
        with:
          configurationFile: renovate/config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
